/**
 * Module orchestrator — executes a single module step in the new architecture.
 *
 * This file implements the engine-side half of the module execution model
 * described in plan.md §2 and §16.
 *
 * ── Execution flow ───────────────────────────────────────────────────────────
 *
 *   executeModuleStep(module, artifactStore, context)
 *        │
 *        ├─ 1. assertEngineContract(module)          validate contract
 *        ├─ 2. assertArtifactsAvailable(...)         enforce consumes
 *        ├─ 3. readArtifactsByType(...)              gather input data
 *        ├─ 4. module.buildPayload(artifacts)        module assembles payload
 *        ├─ 5. runClaira(kind, payload, context)     engine executes (per kind)
 *        ├─ 6. module.normalizeToArtifacts(results)  module normalizes output
 *        ├─ 7. buildArtifact(...) + writeArtifact()  store each output
 *        └─ 8. return { producedArtifacts, engineResults }
 *
 * ── Constraints ──────────────────────────────────────────────────────────────
 *   - workflowExecutor.js is NOT touched — old execute(context) path is unchanged.
 *   - Existing modules are NOT modified.
 *   - Pipelines are NEVER called directly.
 *   - The engine handler map is NEVER accessed directly — only through runClaira().
 *   - All execution goes through runClaira().
 *   - All data transfer between steps goes through artifactStore.
 *
 * ── Context shape ────────────────────────────────────────────────────────────
 *   sessionId       string         Scopes the artifact store to a user session.
 *   workflowRunId   string         Scopes the artifact store to a specific run.
 *   accountId?      string | null  Passed through to runClaira for auth/logging.
 *   rid?            string         Trace ID. Auto-generated by runClaira if absent.
 *
 *   source is always "workflow" for orchestrator calls — callers must not set it.
 *
 * ── normalizeToArtifacts contract ────────────────────────────────────────────
 *   module.normalizeToArtifacts(engineResults, context) must return an array of
 *   partial artifact field objects. The orchestrator merges in the session/run
 *   context and calls buildArtifact() to produce the full validated record.
 *
 *   Each returned object must include:
 *     artifactType     string    Semantic type token (e.g. "EntitySet").
 *     artifactVersion  number    Positive integer.
 *     moduleId         string    Must match module.id.
 *     sourceKind       string    The runClaira kind that produced the data.
 *     data             any       The artifact payload (null for marker artifacts).
 *
 *   Optional (auto-generated if absent):
 *     artifactId       string    UUID.
 *     createdAt        string    ISO 8601 timestamp.
 *
 * ── Vocabulary note ──────────────────────────────────────────────────────────
 *   module.consumes uses ARTIFACT_KINDS tokens ("entity", "event", etc.) for
 *   base contract validation. The runtime artifact store uses typed strings
 *   ("EntitySet", "EventLog", etc.). For source modules (consumes: []) this
 *   causes no issue. Reconciliation for consuming modules is deferred to the
 *   ordering system (Phase 5/6).
 */

import { assertEngineContract } from "../modules/moduleContract.js";
import { runClaira } from "../../server/runClaira.js";
import { buildArtifact } from "../pipeline/runtimeArtifactStore.js";

// =============================================================================
// Typedefs
// =============================================================================

/**
 * @typedef {{
 *   sessionId:      string,
 *   workflowRunId:  string,
 *   accountId?:     string | null,
 *   rid?:           string,
 *   stepId?:        string,
 *   stepIndex?:     number,
 * }} ModuleStepContext
 */

/**
 * @typedef {{
 *   artifactType:    string,
 *   artifactVersion: number,
 *   moduleId:        string,
 *   sourceKind:      string,
 *   data:            unknown,
 *   artifactId?:     string,
 *   createdAt?:      string,
 * }} PartialArtifactFields
 */

/**
 * @typedef {{
 *   kind:   string,
 *   result: unknown,
 * }} EngineCallResult
 */

/**
 * @typedef {{
 *   producedArtifacts: import("../pipeline/runtimeArtifactStore.js").RuntimeArtifact[],
 *   engineResults:     EngineCallResult[],
 * }} ModuleStepResult
 */

// =============================================================================
// Private helpers
// =============================================================================

/**
 * Assert that the step context contains valid sessionId and workflowRunId.
 *
 * @param {unknown} context
 * @returns {ModuleStepContext}
 * @throws {Error}
 */
function normalizeStepContext(context) {
  if (context == null || typeof context !== "object" || Array.isArray(context)) {
    throw new Error("[moduleOrchestrator] context must be a non-null object");
  }
  const c = /** @type {Record<string, unknown>} */ (context);

  if (typeof c.sessionId !== "string" || !c.sessionId.trim()) {
    throw new Error(
      "[moduleOrchestrator] context.sessionId must be a non-empty string — " +
      "the orchestrator requires a session ID to scope the artifact store",
    );
  }
  if (typeof c.workflowRunId !== "string" || !c.workflowRunId.trim()) {
    throw new Error(
      "[moduleOrchestrator] context.workflowRunId must be a non-empty string — " +
      "the orchestrator requires a run ID to scope the artifact store",
    );
  }

  return {
    sessionId:     c.sessionId,
    workflowRunId: c.workflowRunId,
    accountId:     typeof c.accountId === "string" ? c.accountId : null,
    // Auto-generate a trace ID if absent, consistent with runClaira's behaviour.
    rid:           typeof c.rid === "string" && c.rid.trim()
      ? c.rid
      : `orch_${Math.random().toString(36).slice(2, 10)}`,
    // Step identity — passed through from workflowRunner when present.
    stepId:        typeof c.stepId === "string" && c.stepId.trim() ? c.stepId : undefined,
    stepIndex:     typeof c.stepIndex === "number" ? c.stepIndex : undefined,
  };
}

/**
 * Build the consumed artifacts map for a module.
 * Returns an object keyed by artifactType, with each value being the array of
 * artifacts returned by readArtifactsByType for that type.
 *
 * ── Artifact consumption rule (Step-Based Versioned Artifacts) ────────────────
 *
 * The store may contain MULTIPLE artifacts of the same type, produced by
 * different execution steps. Example: two runs of "photo_analysis" at steps
 * A__0 and A__2 both produce "AnalysisBatch" artifacts. Both are preserved.
 *
 * EXECUTION RULE:
 *   When multiple artifacts of the same type are present, modules MUST use
 *   the most recent artifact — the one with the highest stepIndex.
 *   This is always the LAST element in the array returned by
 *   readArtifactsByType(), since artifacts are appended in execution order.
 *
 *     const batch = consumedArtifacts["AnalysisBatch"].at(-1); // most recent
 *
 *   DO NOT consume artifact [0] (oldest) when multiple exist.
 *   DO NOT consume all artifacts — the engine processes one payload at a time.
 *   DO NOT delete earlier artifacts — all versions are retained for the UI
 *   comparison system and the Comparative Analysis Engine (plan.md §21).
 *
 * WHY:
 *   - Deterministic: no ambiguity about which artifact is "active"
 *   - No user interruption: the system auto-selects without a prompt
 *   - Non-destructive: earlier versions remain accessible for history/comparison
 *
 * The UI is responsible for surfacing multiple versions when they exist
 * (plan.md §20). The module orchestrator is responsible for always selecting
 * the most recent for downstream execution.
 *
 * @param {import("../pipeline/runtimeArtifactStore.js").RuntimeArtifactStore} artifactStore
 * @param {string} sessionId
 * @param {string} workflowRunId
 * @param {string[]} consumedTypes
 * @returns {Record<string, import("../pipeline/runtimeArtifactStore.js").RuntimeArtifact[]>}
 */
function buildConsumedArtifactsMap(artifactStore, sessionId, workflowRunId, consumedTypes) {
  /** @type {Record<string, import("../pipeline/runtimeArtifactStore.js").RuntimeArtifact[]>} */
  const map = {};
  for (const type of consumedTypes) {
    map[type] = artifactStore.readArtifactsByType(sessionId, workflowRunId, type);
  }
  return map;
}

/**
 * Assert that normalizeToArtifacts returned a valid, non-empty array.
 * Individual record validity is checked by buildArtifact; this guards the
 * array shape itself.
 *
 * @param {unknown} result
 * @param {string} moduleId
 * @throws {Error}
 */
function assertNormalizeResult(result, moduleId) {
  if (!Array.isArray(result)) {
    throw new Error(
      `[moduleOrchestrator] module "${moduleId}".normalizeToArtifacts() must return an array, ` +
      `got ${typeof result}`,
    );
  }
  for (let i = 0; i < result.length; i++) {
    if (result[i] == null || typeof result[i] !== "object" || Array.isArray(result[i])) {
      throw new Error(
        `[moduleOrchestrator] module "${moduleId}".normalizeToArtifacts() result[${i}] must be ` +
        `a non-null object`,
      );
    }
  }
}

// =============================================================================
// Public: executeModuleStep
// =============================================================================

/**
 * Execute a single module step in the new engine-aware module architecture.
 *
 * This is the only permitted way to run a new-architecture module. It enforces:
 *   - Engine contract validation (assertEngineContract)
 *   - Artifact dependency satisfaction before execution
 *   - All engine calls go through runClaira() — no direct handler or pipeline access
 *   - All data transfer goes through the artifact store
 *
 * @param {unknown} module
 *   A module object that must pass assertEngineContract. Must declare engineKinds,
 *   buildPayload, and normalizeToArtifacts in addition to the base contract fields.
 *
 * @param {import("../pipeline/runtimeArtifactStore.js").RuntimeArtifactStore} artifactStore
 *   The shared store for this workflow run. Created once per run by the caller;
 *   passed to every step in the run sequence.
 *
 * @param {ModuleStepContext} context
 *   Must include sessionId and workflowRunId. accountId and rid are forwarded
 *   to runClaira for logging and future auth enforcement.
 *
 * @returns {Promise<ModuleStepResult>}
 * @throws {Error} for contract violations, missing dependencies, engine errors,
 *   or invalid normalizeToArtifacts output.
 */
export async function executeModuleStep(module, artifactStore, context) {
  // ── Step 1: Validate module ──────────────────────────────────────────────
  // assertEngineContract is a strict superset of assertModuleFollowsContract.
  // It requires engineKinds and would reject any legacy module that does not
  // declare it. This is the Phase 4 gate.
  assertEngineContract(module, `module`);

  // Safe cast — assertEngineContract guarantees these fields exist and are valid.
  const m = /** @type {Record<string, unknown>} */ (module);
  const moduleId      = /** @type {string} */   (m.id);
  const engineKinds   = /** @type {string[]} */ (m.engineKinds);
  const consumes      = /** @type {string[]} */ (m.consumes);
  const buildPayload  = /** @type {Function} */ (m.buildPayload);
  const normalizeToArtifacts = /** @type {Function} */ (m.normalizeToArtifacts);

  const tag = `[moduleOrchestrator] module=${moduleId}`;

  // ── Step 2: Validate and normalize context ───────────────────────────────
  const { sessionId, workflowRunId, accountId, rid, stepId, stepIndex } = normalizeStepContext(context);

  console.log(
    `${tag} start` +
    ` sessionId=${sessionId} runId=${workflowRunId}` +
    (stepId ? ` stepId=${stepId}` : "") +
    ` kinds=[${engineKinds.join(", ")}]` +
    ` consumes=[${consumes.join(", ") || "none"}]`,
  );

  // ── Step 3: Assert required input artifacts are available ─────────────────
  // Fails visibly if any consumed type is missing — never silently skipped.
  // For source modules (consumes: []), this is a no-op.
  if (consumes.length > 0) {
    artifactStore.assertArtifactsAvailable(sessionId, workflowRunId, consumes);
  }

  // ── Step 3b: Read input artifacts into a typed map ────────────────────────
  // Passed to buildPayload so the module can access prior step outputs.
  const consumedArtifacts = buildConsumedArtifactsMap(
    artifactStore, sessionId, workflowRunId, consumes,
  );

  // ── Step 4: Build the engine payload ─────────────────────────────────────
  // The module transforms its consumed artifacts into the payload shape that
  // the engine handler expects. No engine logic lives here.
  let payload;
  try {
    payload = buildPayload(consumedArtifacts, { sessionId, workflowRunId, accountId, rid });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    throw new Error(`${tag} buildPayload() threw: ${msg}`);
  }

  if (payload == null || typeof payload !== "object") {
    throw new Error(
      `${tag} buildPayload() must return a non-null object, got ${typeof payload}`,
    );
  }

  // ── Step 5: Call the engine for each declared kind ────────────────────────
  // All calls go through runClaira() — the handler map is never accessed here.
  // source is always "workflow" for orchestrator calls.
  //
  // DESIGN NOTE — single payload for all kinds:
  // The same payload object is passed to every kind in engineKinds. This is
  // correct for the preferred case (1 module → 1 kind) and acceptable for
  // modules that call a small set of related kinds with compatible payload
  // shapes (plan.md §16 Rule 2).
  //
  // If a future module needs a structurally different payload per kind, add
  // `kind` as a third argument to buildPayload:
  //
  //   module.buildPayload(consumedArtifacts, context, kind) → kindPayload
  //
  // This is backward-compatible: modules that ignore the third argument work
  // unchanged. Do not implement until a concrete multi-kind module requires it.
  /** @type {EngineCallResult[]} */
  const engineResults = [];

  for (const kind of engineKinds) {
    console.log(`${tag} engine kind=${kind} start`);
    const started = Date.now();

    let result;
    try {
      result = await runClaira(kind, /** @type {Record<string, any>} */ (payload), {
        accountId,
        rid,
        source: "workflow",
      });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      throw new Error(
        `${tag} runClaira("${kind}") failed: ${msg}`,
      );
    }

    console.log(`${tag} engine kind=${kind} ms=${Date.now() - started}`);
    engineResults.push({ kind, result });
  }

  // ── Step 6: Normalize engine output to artifacts ──────────────────────────
  // The module maps the raw engine results to partial artifact field objects.
  // The orchestrator owns adding sessionId, workflowRunId, rid, and calling
  // buildArtifact() to produce the full validated record.
  let rawArtifacts;
  try {
    rawArtifacts = normalizeToArtifacts(engineResults, { sessionId, workflowRunId, accountId, rid });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    throw new Error(`${tag} normalizeToArtifacts() threw: ${msg}`);
  }

  assertNormalizeResult(rawArtifacts, moduleId);

  // ── Step 7: Build validated artifact records and write to store ───────────
  // buildArtifact() validates the full schema and auto-generates artifactId
  // and createdAt. writeArtifact() validates again (defence-in-depth) and logs.
  /** @type {import("../pipeline/runtimeArtifactStore.js").RuntimeArtifact[]} */
  const producedArtifacts = [];

  for (const raw of rawArtifacts) {
    const rawFields = /** @type {Record<string, unknown>} */ (raw);

    const artifact = buildArtifact({
      artifactType:    /** @type {string} */  (rawFields.artifactType),
      artifactVersion: /** @type {number} */  (rawFields.artifactVersion),
      moduleId:        /** @type {string} */  (rawFields.moduleId),
      sourceKind:      /** @type {string} */  (rawFields.sourceKind),
      data:            rawFields.data,
      sessionId,
      workflowRunId,
      rid:             rid ?? "",
      // Step lineage — stamped when the orchestrator is called through the runner.
      // Undefined when executeModuleStep is called directly without step context.
      producedByStepId: stepId,
      stepIndex,
      // Pass through optional fields if the module provided them.
      ...(typeof rawFields.artifactId === "string" && rawFields.artifactId ? { artifactId: rawFields.artifactId } : {}),
      ...(typeof rawFields.createdAt === "string" && rawFields.createdAt  ? { createdAt:  rawFields.createdAt }  : {}),
    });

    artifactStore.writeArtifact(artifact);
    producedArtifacts.push(artifact);
  }

  console.log(
    `${tag} done` +
    ` produced=${producedArtifacts.length} artifact(s)` +
    ` [${producedArtifacts.map((a) => a.artifactType).join(", ")}]`,
  );

  // ── Step 8: Return result ─────────────────────────────────────────────────
  return { producedArtifacts, engineResults };
}
